### ISSUE TITLE
comments field

### ISSUE THREAD

**Issue by kenrector** [rzzzwilson/pymlac#24]
Nice assembler. 

But, I found that lines ended with a comment delimiter (;) don't have the preceding fields converted to upper case.  I added a couple of calls to strupper() to correct this at the early returns in delimfields()

**Comment by rzzzwilson** [comment]
Thanks for the report.  I've made the appropriate changes.  Note that the *iasm* assembler is an older version written in C.  The latest version is *pyasm* which is written in python.
